import java.rmi.Remote;

/*
Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.


*/
public class fibonacciEvenSum {
    public static int check(int num){
        int y=0,x,sum=0,preNum = 2 ;
        for(int limit = 1 ; limit<num/3 ; limit++){
            x = y*4+preNum;
            preNum = y;
            y = x ;
            sum+=x;
        }
        return ((num == 0||num==1)? 0 : sum);
    }
    public static void main(String[] args) {
        System.out.println(check(60));    
    }
}
